# baseURL 변경
baseURL = "/"
languageCode = "ko-KR"
defaultContentLanguage = "ko"

# title 변경
title = "AWS DeepLens를 이용한 얼굴 인식 기기 만들기"
theme = "hugo-theme-learn"
themesdir = "."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
#ignoreFiles = [ "\\.*lab3\\.*" ]

# description, author 변경
[params]
  description = "AWS DeepLens 와  Amazon Rekognition 을 이용한 얼굴 인식 기기 만들기"
  author = "SeBeom Lee"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages.ko]
title = "AWS DeepLens를 이용한 얼굴 인식 기기 만들기"
weight = 1
languageName = "한국어"

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> 크레딧"
url = "/credits/"
weight = 30
