# baseURL 변경
baseURL = "/emc-on-the-fly-workshop/"
languageCode = "ko-KR"
defaultContentLanguage = "ko"

# title 변경
title = "Elemental MediaConvert 를 이용한 On-the-Fly HLS 배포"
theme = "hugo-theme-learn"
themesdir = "."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

# description, author 변경
[params]
  description = "Elemental MediaConvert 를 이용한 On-the-Fly HLS 배포"
  author = "SeBeom Lee"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages.ko]
title = "Elemental MediaConvert 를 이용한 On-the-Fly HLS 배포"
weight = 1
languageName = "한국어"

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> 크레딧"
url = "/credits/"
weight = 30
